language: cpp 
before_install:
  - export LD_LIBRARY_PATH=/usr/lib/llvm-${LLVM_VERSION}/lib/
  - export PATH=/usr/lib/llvm-${LLVM_VERSION}/bin:$PATH
  - pwd
matrix:
  include:
    # The default build:
    - &libclang-35
      addons: {apt: {sources: [ubuntu-toolchain-r-test, llvm-toolchain-precise-3.5], packages: [libclang-3.5-dev, clang-3.5]}}
      env: LLVM_VERSION=3.5

script: make -j
