language: cpp
#compiler: clang
matrix:
  include:
    # The default build:
    - &libclang-34
      compiler: clang
      addons:
        apt:
          packages: []
      env: COMPILER=clang++-3.4
  exclude:
    - &libclang-35
      addons: {apt: {sources: [ubuntu-toolchain-r-test, llvm-toolchain-precise-3.5, kalakris-cmake], packages: [libclang-3.5-dev, clang-3.5, clang-3.5-dev, llvm-3.5, llvm-3.5-dev]}}
      env: COMPILER=clang++-3.5 CC=clang-3.5 CXX=clang++-3.5

before_install:
  - export LD_LIBRARY_PATH=/usr/lib/llvm-${LLVM_VERSION}/lib/
  - export PATH=/usr/lib/llvm-${LLVM_VERSION}/bin:$PATH

  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi
  ############################################################################
  # Install libc++ and libc++abi (on Linux only; Xcode uses libc++ by default)
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${STDLIB}" != "libstdc++" ]]; then
      if   [[ "${COMPILER}" == "clang++-3.4" ]]; then LLVM_VERSION="3.4.2"; LLVM_TAR_SUFFIX=".src.tar.gz";
      elif [[ "${COMPILER}" == "clang++-3.5" ]]; then LLVM_VERSION="3.5.2"; LLVM_TAR_SUFFIX=".src.tar.xz";
      elif [[ "${COMPILER}" == "clang++-3.6" ]]; then LLVM_VERSION="3.6.2.src.tar.xz"; LLVM_TAR_SUFFIX=".src.tar.xz";
      elif [[ "${COMPILER}" == "clang++-3.7" ]]; then LLVM_VERSION="3.7.1.src.tar.xz"; LLVM_TAR_SUFFIX=".src.tar.xz";
      elif [[ "${COMPILER}" == "clang++-3.8" ]]; then LLVM_VERSION="3.8.0.src.tar.xz"; LLVM_TAR_SUFFIX=".src.tar.xz";
      else                                            LLVM_VERSION="trunk"; LLVM_TAR_SUFFIX=".src.tar.xz";
      fi
      if [[ "${LLVM_VERSION}" != "trunk" ]]; then
        LLVM_URL="http://llvm.org/releases/${LLVM_VERSION}/llvm-${LLVM_VERSION}${LLVM_TAR_SUFFIX}"
        LIBCXX_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxx-${LLVM_VERSION}${LLVM_TAR_SUFFIX}"
        LIBCXXABI_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxxabi-${LLVM_VERSION}${LLVM_TAR_SUFFIX}"

        if [[ "${LLVM_TAR_SUFFIX}" == ".src.tar.gz" ]]; then
          TAR_FLAGS="-xz"
        else
          TAR_FLAGS="-xJ"
        fi
      else
        LLVM_URL="https://github.com/llvm-mirror/llvm/archive/master.tar.gz"
        LIBCXX_URL="https://github.com/llvm-mirror/libcxx/archive/master.tar.gz"
        LIBCXXABI_URL="https://github.com/llvm-mirror/libcxxabi/archive/master.tar.gz"
        TAR_FLAGS="-xz"
      fi
      mkdir -p llvm llvm/build llvm/projects/libcxx llvm/projects/libcxxabi
      travis_retry wget --quiet -O - ${LLVM_URL} | tar --strip-components=1 ${TAR_FLAGS} -C llvm
      travis_retry wget --quiet -O - ${LIBCXX_URL} | tar --strip-components=1 ${TAR_FLAGS} -C llvm/projects/libcxx
      travis_retry wget --quiet -O - ${LIBCXXABI_URL} | tar --strip-components=1 ${TAR_FLAGS} -C llvm/projects/libcxxabi
      (cd llvm/build && cmake .. -DCMAKE_INSTALL_PREFIX=${DEPS_DIR}/llvm/install -DCMAKE_CXX_COMPILER=clang++)
      (cd llvm/build/projects/libcxx && make install -j2)
      (cd llvm/build/projects/libcxxabi && make install -j2)
      export CXXFLAGS="-isystem ${DEPS_DIR}/llvm/install/include/c++/v1"
      export LDFLAGS="-L ${DEPS_DIR}/llvm/install/lib -l c++ -l c++abi"
      export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DEPS_DIR}/llvm/install/lib"
    fi

script:
  - env
  - cd ${TRAVIS_BUILD_DIR}
  - test -d build || mkdir build
  - cd build ; test -e Makefile || cmake -D CMAKE_BUILD_TYPE=RelWithDebInfo -D BRO_DIST=${BRO_DIST} .. ;
  - make VERBOSE=1 -j
